# When `visual-regression-diff-build` start. Leave a message on the PR
#
# 🚨🚨🚨 Important 🚨🚨🚨
# Never do any `checkout` or `npm install` action!
# `pull_request_target` will enable PR to access the secrets!

name: 👀 Visual Regression Diff Start

on:
  workflow_run:
    workflows: ["👀 Visual Regression Diff Build"]
    types:
      - in_progress

permissions:
  contents: read

jobs:
  visual-regression-diff-start:
    permissions:
      issues: write  # for actions-cool/maintain-one-comment to modify or create issue comments
      pull-requests: write  # for actions-cool/maintain-one-comment to modify or create PR comments
    name: start visual-regression diff
    runs-on: ubuntu-latest
    steps:
      - name: update status comment
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Visual-Regression Diff Build Start
            👀 📊 🔄 🔍 🐞
            <!-- VISUAL_DIFF_REGRESSION_HOOK -->
          body-include: '<!-- VISUAL_DIFF_REGRESSION_HOOK -->'
